import { auth } from '@clerk/nextjs/server'
import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase/server'
import Anthropic from '@anthropic-ai/sdk'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

async function getGithubToken(userId: string): Promise<string | null> {
  const supabase = createServiceClient()
  const { data } = await supabase
    .from('user_integrations')
    .select('access_token')
    .eq('user_id', userId)
    .eq('provider', 'github')
    .single()
  return data?.access_token ?? null
}

// POST /api/github/create-pr
// body: { repo, path, fileContent, description, projectName }
export async function POST(req: NextRequest) {
  const { userId } = await auth()
  if (!userId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { repo, path, fileContent, description, projectName } = await req.json()
  if (!repo || !path || !fileContent || !description) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  const token = await getGithubToken(userId)
  if (!token) return NextResponse.json({ error: 'GitHub not connected' }, { status: 400 })

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  }

  // 1. Get default branch
  const repoRes = await fetch(`https://api.github.com/repos/${repo}`, { headers })
  if (!repoRes.ok) return NextResponse.json({ error: 'Could not fetch repo' }, { status: 400 })
  const repoData = await repoRes.json()
  const defaultBranch = repoData.default_branch ?? 'main'

  // 2. Get current SHA of default branch
  const refRes = await fetch(`https://api.github.com/repos/${repo}/git/ref/heads/${defaultBranch}`, { headers })
  if (!refRes.ok) return NextResponse.json({ error: 'Could not get branch ref' }, { status: 400 })
  const refData = await refRes.json()
  const sha = refData.object.sha

  // 3. Use Claude to generate the modified file
  const aiRes = await anthropic.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 4096,
    messages: [{
      role: 'user',
      content: `You are modifying a UI file for a project called "${projectName ?? 'my project'}".

File path: ${path}

Current file content:
\`\`\`
${fileContent.slice(0, 8000)}
\`\`\`

Requested UI change: ${description}

Return ONLY the complete modified file content, no explanation, no markdown code blocks, no preamble. Just the raw file content.`,
    }],
  })

  const newContent = (aiRes.content[0] as { type: string; text: string }).text.trim()
    .replace(/^```[\w]*\n/, '').replace(/\n```$/, '') // strip any code fences

  // 4. Create a new branch
  const branchName = `forge-ui/${Date.now()}`
  const createBranchRes = await fetch(`https://api.github.com/repos/${repo}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha }),
  })
  if (!createBranchRes.ok) return NextResponse.json({ error: 'Could not create branch' }, { status: 500 })

  // 5. Get current file SHA (needed for update)
  const fileRes = await fetch(`https://api.github.com/repos/${repo}/contents/${path}`, { headers })
  const fileData = fileRes.ok ? await fileRes.json() : null
  const fileSha = fileData?.sha

  // 6. Commit the changed file to the new branch
  const commitRes = await fetch(`https://api.github.com/repos/${repo}/contents/${path}`, {
    method: 'PUT',
    headers,
    body: JSON.stringify({
      message: `UI change: ${description.slice(0, 72)}`,
      content: Buffer.from(newContent).toString('base64'),
      branch: branchName,
      ...(fileSha ? { sha: fileSha } : {}),
    }),
  })
  if (!commitRes.ok) return NextResponse.json({ error: 'Could not commit changes' }, { status: 500 })

  // 7. Create PR
  const prRes = await fetch(`https://api.github.com/repos/${repo}/pulls`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      title: `UI: ${description.slice(0, 72)}`,
      body: `Generated by Forge UI Customize.\n\n**File:** \`${path}\`\n**Change:** ${description}`,
      head: branchName,
      base: defaultBranch,
    }),
  })
  if (!prRes.ok) return NextResponse.json({ error: 'Could not create PR' }, { status: 500 })

  const prData = await prRes.json()
  return NextResponse.json({ prUrl: prData.html_url, branch: branchName })
}
